export const LumiColors = {
  light: {
    background: '#F8F9FF',
    surface: '#FFFFFF',
    surfaceSecondary: '#F0F2FF',
    surfaceElevated: '#ECEFFE',
    primary: '#5B5FEF',
    accent: '#FF6B6B',
    success: '#00C896',
    warning: '#FFB547',
    danger: '#FF4757',
    text: '#1A1D2E',
    textMuted: '#8B8FA8',
    border: '#E8EAFF',
    tabBar: '#FFFFFF',
    tabBarBorder: '#E8EAFF',
  },
  dark: {
    background: '#0A0A0F',
    surface: '#13131A',
    surfaceSecondary: '#1C1C26',
    surfaceElevated: '#1C1C26',
    primary: '#6B70FF',
    accent: '#FF7A7A',
    success: '#00E5A0',
    warning: '#FFB547',
    danger: '#FF5566',
    text: '#F0F0FF',
    textMuted: '#8888AA',
    border: '#2A2A3A',
    tabBar: '#13131A',
    tabBarBorder: '#2A2A3A',
  },
} as const;

export type ThemeColors = typeof LumiColors.light | typeof LumiColors.dark;
